### ISSUE TITLE
Update修改时间字段会报错

### ISSUE THREAD

**Issue by QishengRan** [SkyChenSky/Sikiro.Dapper.Extension#17]
System.InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.PropertyExpression' to type 'System.Linq.Expressions.ConstantExpression'.
    at Sikiro.Dapper.Extension.Expressions.UpdateExpression.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Sikiro.Dapper.Extension.Expressions.UpdateExpression..ctor(LambdaExpression expression, ProviderOption providerOption)
   at Sikiro.Dapper.Extension.MsSql.MsSqlProvider.FormatUpdate[T](Expression`1 updateExpression)
   at Sikiro.Dapper.Extension.Core.SetC.Command`1.Update(Expression`1 updateExpression)

**Comment by QishengRan** [comment]
var i = context.Connection.CommandSet<MemberDO>()
                        .Where(o => o.Id == 10007)
                        .Update(o => new MemberDO
                        {
                            LoginDate = DateTime.Now
                        });
